config/routes.rb
Sorteando::Application.routes.draw do
  resources :sorteios do
    member do
      get :sortear
    end
    resources :concorrentes, :only => [:new, :create, :destroy]
  end
  
  root :to => 'sorteios#index'
end

app/models/concorrente.rb
# encoding: UTF-8
class Concorrente < ActiveRecord::Base
  validates_presence_of :nome, :message => "é um campo obrigatório"
  belongs_to :sorteio
  
  def eh_vencedor?
    VencedorSorteio.where(:concorrente_id => self).exists?
  end
end

app/models/sorteio.rb
# encoding: UTF-8
class Sorteio < ActiveRecord::Base
  validates_presence_of :nome, :message => "é um campo obrigatório"
  validates_presence_of :qtd_premios, :message => "é um campo obrigatório"
  
  has_many :concorrentes, :dependent => :destroy
  has_many :vencedores_sorteios, :class_name => 'VencedorSorteio', :dependent => :destroy
  has_many :vencedores, :through => :vencedores_sorteios, :source => :concorrente

  def sortear
    concorrentes = Concorrente.where(:sorteio_id => self.id).map{|x| x.id}
    [self.qtd_premios, concorrentes.size].min.times do
      vencedor = concorrentes.sample
      concorrentes.delete(vencedor)
      self.vencedores << Concorrente.find(vencedor)
    end
    self.save!
  end
end

app/models/vencedor_sorteio.rb
class VencedorSorteio < ActiveRecord::Base
  belongs_to :sorteio
  belongs_to :concorrente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/concorrentes_controller.rb
# encoding: UTF-8
class ConcorrentesController < ApplicationController

  def new
    @concorrente = Concorrente.new
    @concorrente.sorteio = Sorteio.find(params[:sorteio_id])
  end

  def create
    @concorrente = Concorrente.new(params[:concorrente])
    if @concorrente.save
      redirect_to sorteio_path(@concorrente.sorteio_id), notice: 'Concorrente criado.'
    else
      redirect_to sorteio_path(@concorrente.sorteio_id), notice: 'Houve um erro na criação do Concorrente.'
    end
  end

  def destroy
    @concorrente = Concorrente.find(params[:id])
    sorteio_id = @concorrente.sorteio_id
    @concorrente.destroy
    
    redirect_to sorteio_path(sorteio_id)
  end
end

app/controllers/sorteios_controller.rb
# encoding: UTF-8
class SorteiosController < ApplicationController

  # GET /sortear
  def sortear
    @sorteio = Sorteio.find(params[:id])
    @sorteio.sortear
    redirect_to sorteio_path(@sorteio_id), notice: 'Sorteio realizado.'
  end

  # GET /sorteios
  # GET /sorteios.json
  def index
    @sorteios = Sorteio.all
  end

  # GET /sorteios/1
  # GET /sorteios/1.json
  def show
    @sorteio = Sorteio.find(params[:id])
  end

  # GET /sorteios/new
  # GET /sorteios/new.json
  def new
    @sorteio = Sorteio.new
  end

  # GET /sorteios/1/edit
  def edit
    @sorteio = Sorteio.find(params[:id])
  end

  # POST /sorteios
  # POST /sorteios.json
  def create
    @sorteio = Sorteio.new(params[:sorteio])
    if @sorteio.save
      redirect_to @sorteio, notice: 'Sorteio criado.'
    else
      render action: "new"
    end
  end

  # PUT /sorteios/1
  # PUT /sorteios/1.json
  def update
    @sorteio = Sorteio.find(params[:id])
    if @sorteio.update_attributes(params[:sorteio])
      redirect_to @sorteio, notice: 'Sorteio atualizado.'
    else
      render action: "edit"
    end
  end

  # DELETE /sorteios/1
  # DELETE /sorteios/1.json
  def destroy
    @sorteio = Sorteio.find(params[:id])
    @sorteio.destroy
    redirect_to sorteios_url, notice: 'Sorteio removido.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sorteios_helper.rb
module SorteiosHelper
  def sorteio_encerrado?(sorteio)
    sorteio.vencedores.any?
  end

end

app/views/concorrentes/new.html.erb
<h1>Novo Concorrente</h1>

<%= form_for(@concorrente, :url => {:action => :create, :controller => :concorrentes, :sorteio_id => @concorrente.sorteio.id}) do |f| %>

  <%= f.label :nome, "Nome" %>
  <%= f.text_field :nome %>
  <%= f.hidden_field :sorteio_id %>

  <div class="actions">
    <%= f.submit "Novo" %>
  </div>
<% end %>

<%= link_to '⇤', sorteio_path(@concorrente.sorteio_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorteando</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sorteios/_form.html.erb
<%= form_for(@sorteio) do |f| %> 
  <%= f.label :nome, "Nome" %>
  <%= f.text_field :nome %>
  <br/>
  <%= f.label :qtd_premios, "Qtd de Premios" %>
  <%= f.text_field :qtd_premios %>
  <div class="actions">
    <%= f.submit text_button %>
  </div>
<% end %>

app/views/sorteios/edit.html.erb
<h1>Editar Sorteio</h1>

<%= render 'form', :text_button => 'Editar' %>

<%= link_to '☉', @sorteio %> |
<%= link_to '⇤', sorteios_path %>

app/views/sorteios/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Sorteios</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sorteios.each do |sorteio| %>
  <tr>
	<td><%= sorteio.nome %></td>
    <td><%= link_to '☉', sorteio %></td>
    <td><%= link_to '✎', edit_sorteio_path(sorteio) %></td>
    <td><%= link_to '✄', sorteio, :action => :destroy, :confirm => 'Tem certeza?', :method => :delete %></td>
	
  </tr>
<% end %>
</table>

<br />

<%= link_to '+', new_sorteio_path %>

app/views/sorteios/new.html.erb
<h1>Novo Sorteio</h1>

<%= render 'form', :text_button => 'Novo' %>

<%= link_to '⇤', sorteios_path %>

app/views/sorteios/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
<%= @sorteio.nome %>
</h2>
<% if not sorteio_encerrado?(@sorteio) %>
<%= link_to '⌘ Sortear', sortear_sorteio_path(@sorteio) %>
	<br/><br/>
<% end %>

Concorrentes:
<br/>
<% @sorteio.concorrentes.each do |c| %>
	<%= c.nome %>
	<% if not sorteio_encerrado?(@sorteio) %>
		<%= link_to '✄', sorteio_concorrente_path(@sorteio, c), confirm: 'Tem certeza?', :method => :delete %>
	<% end %>
	<br/>
<% end %>

<% if not sorteio_encerrado?(@sorteio) %>
	<%= link_to '+', new_sorteio_concorrente_path(@sorteio) %>
	<br/>
<% end %>
<br/>

<% if sorteio_encerrado?(@sorteio) %>
	Vencedores:
	<br/>
	<% @sorteio.vencedores.each do |v| %>
		<%= v.nome %>
		<br/>
	<% end %>
	<br/>
<% end %>

<%= link_to '✎', edit_sorteio_path(@sorteio) %> |
<%= link_to '⇤', sorteios_path %>